### ISSUE TITLE
Is FPS capped to display Hz?

### ISSUE THREAD

**Issue by kroko** [Syphon/Syphon-Framework#36]
Hi,

Is it true, that, if when using Syphon Server to push frames, FPS will be capped to 60 (display Hz)? Has to do with some intrinsic properties how it binds to OS @ low level?

I have never had need to run _Syphon enabled_ apps before above 60fps.

I am using oF stable branch (0.9.8 tag), current master branch of ofxSyphon, OS X 10.11.6 (15G31) w/ AMD FirePro D700, NSAppSleepDisabled for bunde identifier. However not asking in oF addon repo as first wanted to understand is it SyphonFramework behaviour, that the addon only extends.

If no and there is no capping, I will ask @astellato about the oF & ofxSyphon.

Thanks!

---

My test has
```cpp
ofSetFrameRate(120);
ofSetVerticalSync(false);
```

and 

```cpp
syphonServerTex.publishTexture(&someFbo.getTexture());
```

Whenever I comment out the tex publishing (that one line above, not delinking Syphon), app reports 120fps as expected.
When tex publishing line is present it caps to 60fps.

**Comment by vade** [comment]
Huh.

I just tried this is Quartz Composer and can re-create. 

This could be do with how we flush / synchronize resources across context - a requirement to ensure the IOSurface backed between applications is updated, but the flush should NOT be dependent on screen refresh. 

Interesting. 

@bangnoise - Perhaps this is something to do with specific implementations of the server, and not the framework? I can't imagine why that would be off the top of my head.

**Comment by vade** [comment]
Interesting. This only happens in Quartz if I have a Syphon Client enabled. To recreate:

* disable V-sync in private prefs
* restart QC
* Make clear patch,  sprite, LFO. Connect LFO to sprite
* FPS reports in hundreds
* Make Syphon Server patch - set to OpenGL scene, FPS still in hundreds.
* Launch Simple Client. FPS in 60s.

**Comment by kroko** [comment]
Wow, that was fast. :)
Meanwhile I just got in the same place as you, that is, capping happens if there is an active client.
When no client, I get 120fps.
When there is active client (tested with _Simple Client_ helper app as well as _MadMapper_) that is listening to tex, it caps to 60fps.

**Comment by vade** [comment]
Ah. This makes more sense. I think I see whats happening.

Simple Client and Syphon Recorder draw results at 60hz on the screen with VSync.

We share a *single* IOSurface between apps.

If your app is attempting to draw significantly faster than a client might display, a resource contention occurs since when the client is attempting to draw the result right before a screen refresh (on v-sync begin), your app attempts to draw (since its not locked to v-sync). Now you can't because the IOSurface is locked read only for drawing.

Thus, I think you are throttled.

I can remove this issue by *minimizing* the client so it doesnt draw on screen. Then my active record can and QC app returns to running quite fast. 

I think your 'client' should be v-sync disabled too if thats an option.

**Comment by vade** [comment]
Can you mitigate the situations with Simple Client being minimized? Can you recreate by launching Syphon Recorder but removing the preview by doing Command-Y ? Both should report FPS for you in the hundreds I think.

This indicates to me resource contention by the client not being able to 'keep up' with the server so to speak.

**Comment by vade** [comment]
Yea I can have two clients and get QC running at 300FPS if I minimize Simple Client and disable previews from Syphon Recorder. I just recorded the output of an app at 1141FPS (yes, 1000 +) 

![screen shot 2016-11-26 at 6 21 38 pm](https://cloud.githubusercontent.com/assets/65011/20644528/369ed0b8-b405-11e6-8e28-eb3faa1bfcab.png)


Perhaps we should have a v-sync disable pref, or mention this somewhere if you intend to draw faster than your screen. Huh. @bangnoise - am I crazy at arriving at this conclusion?

**Comment by kroko** [comment]
Yes, I can recreate the behaviour.

App that uses Syphon Server set to 120fps with vsync off is drawing at 120fps when publishing a texture at every frame.

If another app connects in the system as Client and starts listening to the Server and
- **displays the data**, FPS at the server app drops to stable 60
- **does not display date**, FPS at the server app goes back to stable 120
Tested on _Simple Client_, _Syphon Recorder_, _MadMapper_.

**Comment by vade** [comment]
Can you connect to a server that does not draw with V-sync?

Syphon framework has an often un-used feature for clients which is a callback based drawing, which would allow for synchronization with server drawing - the newFrameHandler block (or Lambda if you come from another environment).

Using the lambda to draw would evoke your drawing whenever your server sends a frame, rather than relying on two potentially 'out of phase' drawing systems.

However, its unclear if clients like Mad-mapper and friends actually use this feature or implement their own 'v-sync' method.

You might be a bit in edge-case territory here, unfortunately.

May I ask, why do you intend on drawing at 120fps? Is your output device at 120?

**Comment by kroko** [comment]
I just did a fast test, packed together Client and Server both with VSync off and nonclamped FPS (_inf_ value).

As you can see, it sends/receives ~470 fps.

![screen shot 2016-11-27 at 01 51 51](https://cloud.githubusercontent.com/assets/720976/20644640/1dee3ede-b444-11e6-98c9-bc738b7ce611.png)

No, I will not be displaying on 120 Hz device. The reason is hard to explain. It has to do with per frame computations that I need to do, and I want them to be done more frequently to reduce _latency_ as much as possible. There are camera and sensor inputs, that are threaded, but I need to do calculations on them, draw fbos, analyse the fbos, draw fbos again.  Because <placeholder for one does not simply do threaded OpenGL meme> i need my main thread to be as fast as possible. I could improve things a little bit with extra threads and extra signalling, but it would be really hard to separate, serialise and push the stuff around. I hope you got a point.

**Comment by vade** [comment]
Roger that with regard to latency. Makes sense. If you need to use 3rd party tools in your workflow it might be best to speak to the developers of those tools about ways to disable vsync in their apps. I hope we've demonstrated this isn't a specific syphon issue, or at least, its a by-product of resource contention for out of phase drawing timing.

Do you feel you've gotten adequate explanation to close this? Glad the above is demonstrably working.

**Comment by kroko** [comment]
I've threaded everything, including issue posting http://forum.garagecube.com/viewtopic.php?f=21&t=9722 It's done ;)

**Comment by vade** [comment]
Cool - lets keep this open until you get an adequate response just for visibilities sake.

**Comment by vade** [comment]
Looks like you got some good feedback. Closing :)

**Comment by mattbeghin** [comment]
Yes, thanks ! Hope you're doing well.
Cheers
