### ISSUE TITLE
Metal

### ISSUE THREAD

**Issue by lov** [Syphon/Syphon-Framework#44]
Hi there,

since now we are know OpenGL going to be deprecated sooner or later, I'm wondering how you see the future of Syphon? Can all this be done using Metal?  

Thanks!

**Comment by anome** [comment]
@lov Hey, we worked on a Metal implementation last year. Feel free to try this out : https://github.com/anome/Syphon-Framework

We're discussing with Syphon's team if this could be merged (or not).

**Comment by lov** [comment]
Thanks @anome , I'll definitely check out!

**Comment by bangnoise** [comment]
note to self re #49 and Metal support

**Comment by gormster** [comment]
Seems to me like the sensible thing would be to just drop any specific graphics technology stack, and work with IOSurfaces directly. Metal and GL both support it natively, so does Core Video and a handful of other macOS technologies. Could have separate libraries for quick-and-easy implementations for Metal, GL etc. but I don't understand why it's considered in-scope for Syphon.framework which is primarily focused on IPC.

**Comment by bangnoise** [comment]
@gormster because every Metal (or OpenGL) user of the API is going to have to do identical work to use the framework, so that work should be part of the framework - no point us not writing code once if every single user is then going to have to write it for themselves. Currently integrating a Syphon server in an OpenGL app takes about 4(?) lines of code, and we'd like to bring that ease of integration to Metal users too.

Recent refactoring makes it trivial to write your own extensions for other technologies - see the notes near the bottom of [Syphon.h](https://github.com/Syphon/Syphon-Framework/blob/ecf98b1afdabdd596ad6c93d6172bdeb369e6ecb/Syphon.h#L187).

**Comment by bangnoise** [comment]
Note to all that Metal integration is actively under discussion in the PR at #56

**Comment by bangnoise** [comment]
This is done - remaining tasks are tracked under other issues.
